### ISSUE TITLE
Unable to create ResourceGroup with Tags

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure-Samples/azure-samples-net-management#6]
Unable to create a ResourceGroup with the provided code sample in **ManageResourceGroup** project 

![image](https://user-images.githubusercontent.com/8835012/95360235-bb22ff80-08e8-11eb-8608-7d25fda5f92d.png)

I am getting an error 
Property or indexer 'ResourceGroup.Tags' cannot be assigned to -- it is read only

**Comment by ItayPodhajcer** [comment]
The implementation in `1.0.0-preview.2` is different for some reason [ResourceGroup](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Resources_1.0.0-preview.2/sdk/resources/Azure.ResourceManager.Resources/src/Generated/Models/ResourceGroup.cs)
Not very immutability friendly 😕
Maybe code generators related?

**Comment by memontic-ms** [comment]
In version `1.0.0-preview.2` of Azure.ResourceManager.Resources, you should be able to assign to Tags like this:  
`resourceGroup.Tags.Add(resourceTagName, resourceTagValue);`

If your problem presists, you can [open an issue in the azure-sdk-for-net repo](https://github.com/Azure/azure-sdk-for-net/issues/new/choose).
